steps:
  - label: ':hammer: Build Nomad Push artifacts'
    command: 'chmod +x .buildkite/build.sh && .buildkite/build.sh -n cluster_network -s $BUILDKITE_COMMIT -b $BUILDKITE_BRANCH -t $BUILDKITE_TAG'
    plugins:
      docker-login#v2.0.0:
        username: devopsintralox
        password-env: DOCKER_LOGIN_PASSWORD
    agents:
      arch: "x86"